const sidebar = {
    '/base/engine/': [
        '1.index',
        '1.utils',
        '2.project',
        '3.vuecli',
        '4.env',
        '5.ui',
        '6.layout',
        '7.single',
        '8.page',
        '9.module',
        '10.skill',
        '11.mock',
        '12.optimization',
        '13.deploy'
    ],
    '/base/project/': [
        '1.index',
        '1.config',
        '2.skill',
        '3.configureWebpack',
        '4.projectMonitor',
        '5.test',
        '6.configurePrem',
        '7.internationalization',
        '8.errorCollection',
        '9.optimize',
        '10.server',
        '11.pwa',
        '12.upload',
        '13.video'
    ],
    '/base/vue2.x/': [
        '1.index',
        '1.vue-cli',
        '2.vue',
        '2.vue1',
        '2.vue2',
        '2.vue3',
        '2.vue4',
        '3.vue-router',
        '4.vuex',
        '5.ui',
        '6.utils',
        '7.style',
        '8.eslint',
    ],
    '/base/vue3.x/': [
        '1.index',
        '1.vue-cli3',
        '2.vue',
        '2.vue1',
        '3.vue-router',
        '4.vuex',
        '5.ui',
        '6.vueuse'
    ],
    "/base/4.window/": [
        "1.index",
        "1.grammar",
        "2.morphology",
        "3.context",
        "4.variableobj",
        "5.scope",
        "6.closure",
        "7.this",
        "8.async",
        "9.eventloop",
        "10.dom",
        "11.bom",
    ],
    "/base/5.document/": [
        "1.index",
        "1.grammar",
        "2.morphology",
        "3.context",
        "4.variableobj",
        "5.scope",
        "6.closure",
        "7.this"
    ],
    "/base/3.browser/": [
        "1.index",
        "1.compiler",
        "2.garbage",
        "3.context",
        "4.clouser",
        "5.v8",
        "6.performance",
        "16.拖拽和原生拖拽事件",
        "17.手机的 touch gesture 事件模型",
        "22.Ajax 同源策略和跨域",
        "26.内存管理",
    ],
    "/base/4.network/": [
        "1.index",
        "1.http",
        "2.https",
        "3.tcp",
        "4.catch",
        "5.dns",
    ],
    '/senior/1.micro/': [
        '1.index',
        '1.singlespa',
        '2.qiankun',
        '3.share'
    ],
    '/senior/2.typescript/': [
        '1.index',
        '1.env',
        '2.base',
        '3.deduction',
        '4.type',
        '5.class',
        '6.interface',
        '7.generic',
        '8.compatible',
        '9.protect',
        '10.infer',
        '11.overlapping',
        '12.condition',
        '13.builtin',
        '14.package',
        '15.custom',
        '16.unknown',
        '17.module',
        '18.statement',
        '19.extend'
    ],
    '/senior/3.deploy/': [
        '1.index',
        '1.local',
        '2.gitlab',
        '3.genkins',
        '4.centos',
        '5.nginx'
    ],
    '/senior/4.component/': [
        '1.index',
        '1.env',
        '1.recursion',
        '2.dynamics',
        '3.dialog',
        '4.render',
        '6.form',
        '7.checkBox',
        '8.dispaly',
        '9.alert',
        '10.renderTable',
        '11.slotScopeTable',
        '12.tree',
        '13.publish',
    ],
    '/senior/5.garbage/': [
        '1.index',
        '1.local',
        '2.gitlab',
        '3.genkins',
        '4.centos',
        '5.nginx'
    ],
    '/senior/6.webkit/': [
        '1.index',
        '1.local',
        '2.gitlab',
        '3.genkins',
        '4.centos',
        '5.nginx'
    ],
    '/senior/7.engine/': [
        '1.index',
        '1.local',
        '2.gitlab',
        '3.genkins',
        '4.centos',
        '5.nginx'
    ],
    '/senior/8.v8/': [
        '1.index',
        '1.local',
        '2.gitlab',
        '3.genkins',
        '4.centos',
        '5.nginx'
    ],
    '/senior/vue3/': [
        '1.index',
    ],
    '/source/vue-cli2.x/': [
        '1.index'
    ],
    '/source/vue2.x/': [
        '1.index',
        '2.initGlobalAPI',
        '3.initMixin',
        '4.stateMixin',
        '5.eventsMixin',
        '6.lifecycleMixin',
        '7.renderMixin',
        '8.mount',
        '9.ast',
        '10.optimize',
        '11.gencode',
        '12.mount',
        '13._render',
        '14._update'
    ],
    '/source/vue-router3.x/': [
        '1.index',
        '2.origin'
    ],
}
module.exports = sidebar